[package]
name = "gtv-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "gtv-server"
path = "src/main.rs"

[dependencies]
gtv-core = { path = "../gtv-core" }
gtv-engine = { path = "../gtv-engine" }
gtv-proto = { path = "../gtv-proto" }
arrow.workspace = true
anyhow.workspace = true
tokio.workspace = true
tonic.workspace = true

[dev-dependencies]
gtv-proto = { path = "../gtv-proto" }
arrow.workspace = true
tokio.workspace = true
