[package]
name = "gtv-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
datafusion.workspace = true
arrow.workspace = true
gtv-core = { path = "../gtv-core" }
gtv-array = { path = "../gtv-array" }
gtv-pattern = { path = "../gtv-pattern" }
gtv-storage = { path = "../gtv-storage" }
thiserror.workspace = true
ureq = "2"
serde_json = "1"
anyhow.workspace = true
chrono = "0.4"
